# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &defaults

aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

development:
  secret_key_base: 74fbb265495b02fa6630859bc4a023b95c87ab0e7665652f7aa68f8addd35338a1114e2f530f8d27ad461fb16021bf46dbc5a5a5a1d7a0651c3625ad8bf7c79e

test:
  secret_key_base: 3fb9326aabb3fa2ca1158f3f30532c8bb21ca1249a0c8e75d65999516ceff7a140bb0d7863f80006e846571fe848f9e2146949f7e531ad79357cf991b25b1a52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
